In [1]:
import numpy as np

In [14]:
array = np.arange(1899, 2226)

In [15]:
array[(array % 400 == 0) | (array % 4 == 0) & (array % 100 != 0)]

array([1904, 1908, 1912, 1916, 1920, 1924, 1928, 1932, 1936, 1940, 1944,
       1948, 1952, 1956, 1960, 1964, 1968, 1972, 1976, 1980, 1984, 1988,
       1992, 1996, 2000, 2004, 2008, 2012, 2016, 2020, 2024, 2028, 2032,
       2036, 2040, 2044, 2048, 2052, 2056, 2060, 2064, 2068, 2072, 2076,
       2080, 2084, 2088, 2092, 2096, 2104, 2108, 2112, 2116, 2120, 2124,
       2128, 2132, 2136, 2140, 2144, 2148, 2152, 2156, 2160, 2164, 2168,
       2172, 2176, 2180, 2184, 2188, 2192, 2196, 2204, 2208, 2212, 2216,
       2220, 2224])

In [16]:
conditia_1 = array % 400 == 0
conditia_2 = array % 4 == 0
conditia_3 = array % 100 != 0

array[conditia_1 | conditia_2 & conditia_3]

array([1904, 1908, 1912, 1916, 1920, 1924, 1928, 1932, 1936, 1940, 1944,
       1948, 1952, 1956, 1960, 1964, 1968, 1972, 1976, 1980, 1984, 1988,
       1992, 1996, 2000, 2004, 2008, 2012, 2016, 2020, 2024, 2028, 2032,
       2036, 2040, 2044, 2048, 2052, 2056, 2060, 2064, 2068, 2072, 2076,
       2080, 2084, 2088, 2092, 2096, 2104, 2108, 2112, 2116, 2120, 2124,
       2128, 2132, 2136, 2140, 2144, 2148, 2152, 2156, 2160, 2164, 2168,
       2172, 2176, 2180, 2184, 2188, 2192, 2196, 2204, 2208, 2212, 2216,
       2220, 2224])

In [18]:
conditia_2

array([False,  True, False, False, False,  True, False, False, False,
        True, False, False, False,  True, False, False, False,  True,
       False, False, False,  True, False, False, False,  True, False,
       False, False,  True, False, False, False,  True, False, False,
       False,  True, False, False, False,  True, False, False, False,
        True, False, False, False,  True, False, False, False,  True,
       False, False, False,  True, False, False, False,  True, False,
       False, False,  True, False, False, False,  True, False, False,
       False,  True, False, False, False,  True, False, False, False,
        True, False, False, False,  True, False, False, False,  True,
       False, False, False,  True, False, False, False,  True, False,
       False, False,  True, False, False, False,  True, False, False,
       False,  True, False, False, False,  True, False, False, False,
        True, False, False, False,  True, False, False, False,  True,
       False, False,